workspace:
  path: /github.com/elastos/Elastos.ELA

kind: pipeline
name: elastos

clone:
  depth: 10

platform:
  os: linux
  arch: amd64

steps:
- name: unit
  image: golang:1.12
  environment:
    GOPATH: /drone
    GOROOT: /usr/local/go
    GO111MODULE: on
    TEST_BRANCH: master
    GITLAB_URL: "https://gitlab+deploy-token-105635:PLzwmJuKRbbWHtSGDXxx@gitlab.com/elastos/Elastos.ELA.Test.Cases.git"
  commands:
  - curl -o /bin/addlicense http://172.16.0.120/addlicense
  - curl -o /bin/revive http://172.16.120/revive
  - curl -o /bin/checkcoverage http://172.16.120/checkcoverage
  - chmod +x /bin/addlicense /bin/revive /bin/checkcoverage
  - addlicense -check
  - revive -config .revive.toml -formatter friendly -exclude vendor/... $(go list ./...)
  - go test $(go list ./... | grep -v /vendor/) -v -short -coverprofile .coverage
  - go tool cover -func .coverage
  - checkcoverage
  - make dev
  - ./ela -v
  - ./util.sh test
  - git clone -b $TEST_BRANCH --depth 10 $GITLAB_URL
  when:
    event:
    - push
    - pull_request
  #volumes:
  #- name: gopath
  #  path: /go

- name: superTester
  image: "peterwillcn/ela-tester:master"
  environment:
    GOPATH: /drone
    CONF: file://drone/src/github.com/elastos/Elastos.ELA/Elastos.ELA.Test.Cases/config.json
    CASE: file://drone/src/github.com/elastos/Elastos.ELA/Elastos.ELA.Test.Cases/test-cr-case1/registercr.json
  commands:
  - /ela-manager --conf=$CONF --case=$CASE
