stages:
  - unit_test
  - integration_test

job_test1:
  stage: unit_test
  image:
    name: golang:1.12.6-stretch
    entrypoint: ["/bin/sh", "-c"]
  variables:
    GOPATH: /builds/go
    ORG_NAME: "elastos"
    PROJECT_NAME: "Elastos.ELA"
    ORG_DIR: "${GOPATH}/src/github.com/${ORG_NAME}"
  before_script:
    - mkdir -p "${GOPATH}/src"
    - cd "${GOPATH}/src"
    - curl -O http://172.16.0.120/golang.org.tgz
    - curl -O http://172.16.0.120/gopkg.in.tgz
    - curl -O http://172.16.0.120/github.com.tgz
    - tar xf golang.org.tgz
    - tar xf gopkg.in.tgz
    - tar xf github.com.tgz
    - rm -f *.tgz
    - mkdir -p "${ORG_DIR}"
    - ln -s "${CI_PROJECT_DIR}" "${ORG_DIR}/${PROJECT_NAME}"
  script:
    - cd "${ORG_DIR}/${PROJECT_NAME}"
    - curl -o /bin/addlicense http://172.16.0.120/addlicense
    - curl -o /bin/revive http://172.16.120/revive
    - chmod +x /bin/addlicense /bin/revive && addlicense -check
    - revive -config .revive.toml -formatter friendly $(go list ./... | grep -v /vendor/)
    - go test $(go list ./... | grep -v /vendor/) -v -short -coverprofile .coverage
    - go tool cover -func .coverage
    - make all
    - make dns
    - mkdir bin && cp ela ela-cli bin
    - bin/ela -v
    - ./util.sh test
    - cd $CI_PROJECT_DIR
  coverage: '/^total:\t+\(statements\)\t+(\d+\.\d+)%/'
  artifacts:
    name: "$CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID-${CI_BUILD_REF:0:8}"
    paths:
      - bin/

job_test2:
  stage: integration_test
  image: python:3.6-jessie
  variables:
    GOPATH: /builds/go
    ORG_NAME: "elastos"
    PROJECT_NAME: "Elastos.ELA"
    ORG_DIR: "${GOPATH}/src/github.com/${ORG_NAME}"
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  cache:
    paths:
    - $CI_PROJECT_DIR/.cache/pip
  dependencies:
    - job_test1
  before_script:
    - mkdir -p "${ORG_DIR}"
    - ln -s "${CI_PROJECT_DIR}" "${ORG_DIR}/${PROJECT_NAME}"
    - cp bin/* $CI_PROJECT_DIR
    - curl -O http://172.16.0.120/testingwork-testing_work.tar.gz
    - tar xf testingwork-testing_work.tar.gz
  script:
    - python -V
    - ./ela -v
    - cd testingwork-testing_work
    - python -m pip install -r requirements.txt
    - python dpos_normal_test.py
